### ISSUE TITLE
Empty response when trying to query info for cordova-js from API

### ISSUE THREAD

**Issue by raphinesse** [arve0/npm-download-size-api#1]
After about 20 seconds, the following error appears when trying to get info for `cordova-js` from your deployed API.

```
GET https://api.seljebu.no/download-size/cordova-js net::ERR_EMPTY_RESPONSE
```

I haven't had any problems for any other packages so far. Thanks for a great tool.

**Comment by arve0** [comment]
Hi! Thanks for reporting. Server had crashed. Not sure why, nothing in my error logs, but pretty sure I have some bugs to straiten out.

I've restarted the server, let me know if the problem reappear.

**Comment by raphinesse** [comment]
Thanks, everything working fine again. :tada: 

Feel free to close this issue unless you want to keep it open to investigate further.

**Comment by raphinesse** [comment]
It just happened again for `cordova-coho`. Other requests I tried (popular stuff, but not cached by my browser) were answered fine by the API server.

**Comment by arve0** [comment]
I've rolled back latest change, and are refactoring the code to make the API more stable.

**Comment by arve0** [comment]
Fixed, https://arve0.github.io/npm-download-size/#cordova-coho
